name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: make test
    - name: Code Coverage
      run: make coverage
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: f924b101caff1acdcf6ab45dfaa299eb
        filename: ArrowView-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
